"""Output reporting for Hotel Review Analyzer."""

from typing import Any, Dict
from datetime import datetime


def generate_json_report(
    hotel_info: Dict[str, Any],
    classification: Dict[str, Any],
    scoring: Dict[str, Any],
    traveler_profile: Dict[str, Any],
) -> Dict[str, Any]:
    """Generate JSON output report.
    
    Args:
        hotel_info: Hotel information
        classification: Review classification results
        scoring: Risk scoring results
        traveler_profile: Used traveler profile
        
    Returns:
        Complete JSON report
    """
    return {
        "hotel": {
            "name": hotel_info.get("name", "Unknown"),
            "location": hotel_info.get("location", ""),
        },
        "analysis_timestamp": datetime.now().isoformat(),
        "recommendation": scoring["recommendation"],
        "recommendation_score": 100 - scoring["overall_risk_score"],  # Convert to positive score
        "confidence": scoring["confidence"],
        "risk_categories": {
            cat: data["issue_count"]
            for cat, data in scoring.get("category_scores", {}).items()
        },
        "evidence_counts": {
            "total_reviews": classification.get("total_reviews", 0),
            "analyzed_reviews": classification.get("analyzed_reviews", 0),
            "total_issues": scoring.get("total_issues", 0),
        },
        "positive_signals": classification.get("positive_signals", []),
        "negative_signals": classification.get("negative_signals", []),
        "suitable_for": ["general travelers"] if scoring["recommendation"] in ["recommended", "acceptable_with_caveats"] else [],
        "unsuitable_for": ["quiet sleep seekers"] if scoring["category_scores"].get("noise", {}).get("raw_score", 0) > 5.0 else [],
        "pre_booking_checklist": scoring.get("pre_booking_checklist", []),
        "limitations": [
            "Analysis based on text keyword matching only",
            "Does not guarantee actual hotel quality",
            "Review sample may not be representative",
        ],
        "explainability": {
            "rule_trace": scoring.get("rule_trace", {}),
            "weights_used": scoring.get("rule_trace", {}).get("weights_used", {}),
            "traveler_priorities": scoring.get("rule_trace", {}).get("traveler_priorities", {}),
        },
    }


def generate_markdown_report(report: Dict[str, Any]) -> str:
    """Generate Markdown output report.
    
    Args:
        report: JSON report from generate_json_report
        
    Returns:
        Formatted Markdown string
    """
    lines = [
        f"# Hotel Review Analysis: {report['hotel']['name']}",
        "",
        f"**Location:** {report['hotel'].get('location', 'N/A')}",
        f"**Analysis Date:** {report['analysis_timestamp']}",
        "",
        "## Recommendation",
        "",
        f"**Overall Score:** {report['recommendation_score']}/100",
        f"**Recommendation:** {report['recommendation'].replace('_', ' ').title()}",
        f"**Confidence:** {report['confidence'].title()}",
        "",
        "## Risk Summary",
        "",
    ]
    
    risk_cats = report.get("risk_categories", {})
    if risk_cats:
        lines.append("| Category | Issue Count |")
        lines.append("|----------|-------------|")
        for cat, count in risk_cats.items():
            if count > 0:
                lines.append(f"| {cat.replace('_', ' ').title()} | {count} |")
    else:
        lines.append("No significant issues detected.")
    
    lines.extend([
        "",
        "## Evidence Summary",
        "",
        f"- Total reviews analyzed: {report['evidence_counts'].get('analyzed_reviews', 0)}",
        f"- Total issues found: {report['evidence_counts'].get('total_issues', 0)}",
        "",
    ])
    
    checklist = report.get("pre_booking_checklist", [])
    if checklist:
        lines.extend([
            "## Pre-Booking Checklist",
            "",
        ])
        for item in checklist:
            lines.append(f"- [ ] {item}")
        lines.append("")
    
    lines.extend([
        "## Limitations",
        "",
    ])
    for limit in report.get("limitations", []):
        lines.append(f"- {limit}")
    
    lines.extend([
        "",
        "---",
        f"*Generated by Hotel Review Analyzer v0.1.0*",
    ])
    
    return "\n".join(lines)
